export const openingQuestions = [
 'What was your face before anyone gave you a name?',
 'Where does a thought go when it ends?',
 'If a bell rings in your memory, what is vibrating?',
 'Which is closer: yesterday or the moon?',
 'What is the sound of waiting?',
 'When does a shadow begin?',
 'If you lose your way on purpose, are you still lost?',
 'Who arrives first, you or the moment?',
 'What does the room know about you?',
 'If the map is wrong but you arrive, was it wrong?',
 'Where is the edge of now?',
 'Which weighs more: a promise or a stone?',
 'If nobody owns the sky, why do we keep looking up?',
 'What happens to silence when you speak?',
 'If you replace every memory of a place, have you moved?',
 'What is the difference between a door and an opening?',
 'Before you recognize a sound, what is it?',
 'How many times have you entered this room?',
 'If you stop naming colors, does anything become less colorful?',
 'Where was this question before you read it?',
 'If the future never arrives, why are you preparing for it?',
 'Can you point to the exact place where outside becomes inside?',
 'What is a clock measuring when nobody is waiting?',
 'If a river forgets its name, where does it go?',
 'What is the oldest thing you can touch?',
 'If two mirrors face each other, which reflection is the original?',
 'What does your phone become when the battery dies?',
 'If you dream of waking up, which one counts?',
 'What would happen if nothing needed an explanation?',
 'How far away is a memory?',
 'What is the opposite of a question?',
 'If you hear your own voice recorded, who sounds unfamiliar?',
 'When does a path become a detour?',
 'If a machine asks a sincere question, where does the sincerity live?',
 'What is left of a song when it stops?',
 'If the answer changes the question, which one was wrong?',
 'What does darkness look like before your eyes adjust?',
 'If you never finish becoming yourself, who has been here all along?',
 'Which part of a flame is the same flame?',
 'Can something disappear if nobody noticed it was there?',
 'If you throw away a useless object and miss it tomorrow, when did it become valuable?',
 'Where does a joke live before someone laughs?',
 'If you were given one completely ordinary minute, what would make it ordinary?',
 'What is a mistake before anyone notices it?',
 'If a window shows you the world, what does the world see?',
 'Which came first: the boredom or the clock?',
 'If you could ask your reflection one question, would you trust the answer?',
 'What does a city dream about when everyone is asleep?',
 'If you cross a threshold and nothing changes, did you cross it?',
 'Where is the center of a circle drawn badly?',
 'If you forget why you were angry, what happens to the anger?',
 'What is the difference between finding something and noticing it?',
 'If the universe has no audience, why is it so theatrical?',
 'When you close your eyes, what happens to distance?',
 'If nothing is missing, why are you still looking?',
 'What would an empty chair say about absence?',
 'If the same rain falls on two people, is it the same rain?',
 'What is the first thing that changes when you decide something matters?',
 'If your name vanished from every record, what would remain unchanged?',
 'What does a staircase become when nobody goes anywhere?',
] as const;

export function chooseOpening(): string {
 return openingQuestions[Math.floor(Math.random() * openingQuestions.length)];
}
